const lessons = [
{
  num: 1,
  time: "00:00:00,000 --> 00:00:02,600",
  english: "The Drain",
  transcription: "ðə dreɪn",
  parts: null,
  uzbekFull: "Oqova quvuri.",
  note: "drain — oqova quvuri, suv oqadigan quvur.",
},

{
  num: 2,
  time: "00:00:02,600 --> 00:00:07,000",
  english: "[Music]",
  transcription: null,
  parts: null,
  uzbekFull: "[Musiqa]",
  note: null,
},

{
  num: 3,
  time: "00:00:07,000 --> 00:00:11,500",
  english: "Hey Nolik, come help me! The fan and the computer need that.",
  transcription: "heɪ ˈnoʊlɪk kʌm help miː ðə fæn ænd ðə kəmˈpjuːtər niːd ðæt",
  parts: [
    ["Hey Nolik,", "Hey Nolik,"],
    ["come help me!", "kel menga yordam ber!"],
    ["The fan", "Ventilyator"],
    ["and the computer", "va kompyuter"],
    ["need that.", "shunga muhtoj."],
  ],
  uzbekFull: "Hey, Nolik, kel menga yordam ber! Ventilyator va kompyuter bunga muhtoj.",
  note: "SRTdagi 'needs' grammatik jihatdan xato. To'g'risi: 'need'.",
},

{
  num: 4,
  time: "00:00:11,500 --> 00:00:18,000",
  english: "Not right now! Tom Thomas and I are painting a card for his parents' anniversary.",
  transcription: "nɒt raɪt naʊ tɒm ˈtɒməs ænd aɪ ɑːr ˈpeɪntɪŋ ə kɑːrd fər hɪz ˈperənts ænɪˈvɜːrsəri",
  parts: [
    ["Not right now!", "Hozir emas!"],
    ["Tom Thomas and I", "Tom Tomas bilan men"],
    ["are painting", "tayyorlayapmiz"],
    ["a card", "tabrik kartasini"],
    ["for his parents'", "uning ota-onasining"],
    ["anniversary.", "yilligi uchun."],
  ],
  uzbekFull: "Hozir emas! Tom Tomas bilan men uning ota-onasining yubileyi uchun tabrik kartasini tayyorlayapmiz.",
  note: "Tabiiy inglizcha shakli: 'Tom Thomas and I', SRTda 'Me and Tom Thomas' deyilgan.",
},

{
  num: 5,
  time: "00:00:18,000 --> 00:00:22,500",
  english: "Oh! Look at you, you must be so tired! Hi Simka! It's really great you're here.",
  transcription: "oʊ lʊk æt juː juː mʌst biː soʊ ˈtaɪərd haɪ ˈsɪmkə ɪts ˈrɪəli ɡreɪt jʊr hɪr",
  parts: [
    ["Oh!", "Voy!"],
    ["Look at you,", "Senga qara,"],
    ["you must be", "sen bo'lsang kerak"],
    ["so tired!", "juda charchagan!"],
    ["Hi Simka!", "Salom, Simka!"],
    ["It's really great", "Juda yaxshi"],
    ["you're here.", "kelganing."],
  ],
  uzbekFull: "Voy! Senga qara, juda charchagan ko'rinasan! Salom, Simka! Kelganing juda yaxshi bo'ldi.",
  note: null,
},

{
  num: 6,
  time: "00:00:22,500 --> 00:00:27,000",
  english: "I have a question. '12th anniversary' — is it spelled with an F or is it with a V?",
  transcription: "aɪ hæv ə ˈkwestʃən twelfθ ænɪˈvɜːrsəri ɪz ɪt speld wɪð ən ef ɔːr ɪz ɪt wɪð ə viː",
  parts: [
    ["I have", "Menda bor"],
    ["a question.", "bir savol."],
    ["12th anniversary", "\"12th anniversary\""],
    ["is it spelled", "yoziladimi"],
    ["with an F", "F harfi bilan"],
    ["or is it", "yoki"],
    ["with a V?", "V harfi bilan?"],
  ],
  uzbekFull: "Menda bir savol bor. '12th anniversary' F harfi bilan yoziladimi yoki V harfi bilan?",
  note: "spell — so'zni harflab yozmoq.",
},

{
  num: 7,
  time: "00:00:27,000 --> 00:00:29,030",
  english: "Uh, you know what, first put down the number 12, and then put a dash on there, and then a th.",
  transcription: "ʌ juː noʊ wʌt fɜːrst pʊt daʊn ðə ˈnʌmbər twelv ænd ðen pʊt ə dæʃ ɒn ðer ænd ðen ə tiː eɪtʃ",
  parts: [
    ["Uh,", "Hmm,"],
    ["you know what,", "bilasanmi,"],
    ["first", "avval"],
    ["put down", "yoz"],
    ["the number 12,", "12 raqamini,"],
    ["and then", "keyin"],
    ["put", "qo'y"],
    ["a dash", "chiziqchani"],
    ["on there,", "uning yoniga,"],
    ["and then", "va keyin"],
    ["th.", "th qo'shimchasini."],
  ],
  uzbekFull: "Hmm, bilasanmi, avval 12 raqamini yoz, keyin chiziqcha qo'y, undan keyin 'th'ni yoz.",
  note: "dash — chiziqcha (-).",
},
{
  num: 8,
  time: "00:00:30,000 --> 00:00:35,439",
  english: "Oh, right! But first I'll change the water. I'll be right back.",
  transcription: "oʊ raɪt bʌt fɜːrst aɪl tʃeɪndʒ ðə ˈwɔːtər aɪl biː raɪt bæk",
  parts: [
    ["Oh, right!", "Ha, to'g'ri!"],
    ["But first", "Lekin avval"],
    ["I'll change", "men almashtiraman"],
    ["the water.", "suvni."],
    ["I'll be", "Men"],
    ["right back.", "hozir qaytaman."],
  ],
  uzbekFull: "Ha, to'g'ri! Lekin avval suvni almashtiraman. Hozir qaytaman.",
  note: "right back — hozir qaytaman.",
},

{
  num: 9,
  time: "00:00:39,359 --> 00:00:41,359",
  english: "Oh, Mom left her ring here.",
  transcription: "oʊ mɑːm left hər rɪŋ hɪr",
  parts: [
    ["Oh,", "Voy,"],
    ["Mom", "oyim"],
    ["left", "qoldiribdi"],
    ["her ring", "uzugini"],
    ["here.", "shu yerda."],
  ],
  uzbekFull: "Voy, oyim uzugini shu yerda qoldiribdi.",
  note: "SRTdagi 'oh mama left her in here' STT xatosi tuzatildi.",
},

{
  num: 10,
  time: "00:00:44,480 --> 00:00:58,159",
  english: "Whoa! Oh no! What have I done? I spoiled my mom and dad's special day!",
  transcription: "woʊ oʊ noʊ wʌt hæv aɪ dʌn aɪ spɔɪld maɪ mɑːm ænd dædz ˈspeʃəl deɪ",
  parts: [
    ["Whoa!", "Voy!"],
    ["Oh no!", "Yo'q!"],
    ["What have I done?", "Men nima qilib qo'ydim?"],
    ["I spoiled", "Men buzib yubordim"],
    ["my mom and dad's", "oyim bilan dadamning"],
    ["special day!", "maxsus kunini!"],
  ],
  uzbekFull: "Voy! Yo'q! Men nima qilib qo'ydim? Men oyim bilan dadamning maxsus kunini buzib yubordim!",
  note: "SRT oxiridagi 'where in the bathroom' STT xatosi olib tashlandi.",
},

{
  num: 11,
  time: "00:00:58,799 --> 00:01:00,759",
  english: "My mom's ring was lying there,",
  transcription: "maɪ mɑːmz rɪŋ wəz ˈlaɪɪŋ ðer",
  parts: [
    ["My mom's", "Oyimning"],
    ["ring", "uzugi"],
    ["was lying", "yotgandi"],
    ["there,", "u yerda,"],
  ],
  uzbekFull: "Oyimning uzugi u yerda yotgandi.",
  note: null,
},

{
  num: 12,
  time: "00:01:00,919 --> 00:01:04,959",
  english: "and I dropped it into the sink, and now it's washed away.",
  transcription: "ænd aɪ drɒpt ɪt ˈɪntuː ðə sɪŋk ænd naʊ ɪts wɒʃt əˈweɪ",
  parts: [
    ["and I", "va men"],
    ["dropped it", "uni tushirib yubordim"],
    ["into the sink,", "rakovinaga,"],
    ["and now", "va endi"],
    ["it's washed away.", "u oqib ketdi."],
  ],
  uzbekFull: "Va men uni rakovinaga tushirib yubordim, endi esa u oqib ketdi.",
  note: "sink — rakovina.",
},

{
  num: 13,
  time: "00:01:06,159 --> 00:01:07,399",
  english: "There goes the day!",
  transcription: "ðer ɡoʊz ðə deɪ",
  parts: [
    ["There goes", "Barbod bo'ldi"],
    ["the day!", "bu kun!"],
  ],
  uzbekFull: "Bu kun barbod bo'ldi!",
  note: "There goes... — tamom bo'ldi, barbod bo'ldi.",
},

{
  num: 14,
  time: "00:01:07,519 --> 00:01:09,359",
  english: "It didn't wash anywhere!",
  transcription: "ɪt ˈdɪdənt wɒʃ ˈeniwer",
  parts: [
    ["It didn't", "U"],
    ["wash", "oqib ketmadi"],
    ["anywhere!", "hech qayerga!"],
  ],
  uzbekFull: "U hech qayerga oqib ketmadi!",
  note: null,
},

{
  num: 15,
  time: "00:01:09,679 --> 00:01:12,239",
  english: "Don't you know anything about how a drain trap works?",
  transcription: "doʊnt juː noʊ ˈeniθɪŋ əˈbaʊt haʊ ə dreɪn træp wɜːrks",
  parts: [
    ["Don't you know", "Siz bilmaysizmi"],
    ["anything", "hech narsa"],
    ["about", "haqida"],
    ["how", "qanday"],
    ["a drain trap", "oqova quvurining tutqichi"],
    ["works?", "ishlashini?"],
  ],
  uzbekFull: "Oqova quvurining tutqichi qanday ishlashi haqida hech narsa bilmaysizmi?",
  note: "drain trap — rakovina ostidagi egri quvur (suv to'sig'i).",
},
{
  num: 16,
  time: "00:01:12,359 --> 00:01:13,479",
  english: "About a what?",
  transcription: "əˈbaʊt ə wʌt",
  parts: [
    ["About", "Haqida"],
    ["a what?", "nima?"],
  ],
  uzbekFull: "Nima haqida?",
  note: null,
},

{
  num: 17,
  time: "00:01:14,000 --> 00:01:17,079",
  english: "A drain trap is a special curved pipe under the sink basin.",
  transcription: "ə dreɪn træp ɪz ə ˈspeʃəl kɜːrvd paɪp ˈʌndər ðə sɪŋk ˈbeɪsən",
  parts: [
    ["A drain trap", "Oqova quvurining tutqichi"],
    ["is", "bu"],
    ["a special", "maxsus"],
    ["curved pipe", "egri quvur"],
    ["under", "ostidagi"],
    ["the sink basin.", "rakovinaning."],
  ],
  uzbekFull: "Oqova quvurining tutqichi rakovina ostidagi maxsus egri quvurdir.",
  note: "sink basin — rakovina. curved pipe — egri quvur.",
},

{
  num: 18,
  time: "00:01:20,439 --> 00:01:24,039",
  english: "Water flows out of the faucet and flows down into the drain trap,",
  transcription: "ˈwɔːtər floʊz aʊt əv ðə ˈfɔːsɪt ænd floʊz daʊn ˈɪntuː ðə dreɪn træp",
  parts: [
    ["Water", "Suv"],
    ["flows out of", "oqib chiqadi"],
    ["the faucet", "jo'mrakdan"],
    ["and flows down", "va oqib tushadi"],
    ["into", "ichiga"],
    ["the drain trap,", "oqova quvurining tutqichiga,"],
  ],
  uzbekFull: "Suv jo'mrakdan oqib chiqadi va oqova quvurining tutqichiga oqib tushadi.",
  note: "faucet — jo'mrak.",
},

{
  num: 19,
  time: "00:01:24,159 --> 00:01:26,079",
  english: "and after that it goes down to the sewer.",
  transcription: "ænd ˈæftər ðæt ɪt ɡoʊz daʊn tə ðə ˈsuːər",
  parts: [
    ["and after that", "va shundan keyin"],
    ["it goes down", "u oqib ketadi"],
    ["to the sewer.", "kanalizatsiyaga."],
  ],
  uzbekFull: "Va shundan keyin u kanalizatsiyaga oqib ketadi.",
  note: "sewer — kanalizatsiya.",
},

{
  num: 20,
  time: "00:01:26,879 --> 00:01:29,959",
  english: "But when you turn off the water, not all of it washes away.",
  transcription: "bʌt wen juː tɜːrn ɔːf ðə ˈwɔːtər nɒt ɔːl əv ɪt ˈwɒʃɪz əˈweɪ",
  parts: [
    ["But", "Lekin"],
    ["when", "qachonki"],
    ["you turn off", "siz o'chirsangiz"],
    ["the water,", "suvni,"],
    ["not all of it", "uning hammasi emas"],
    ["washes away.", "oqib ketadi."],
  ],
  uzbekFull: "Lekin suvni o'chirganingizda, uning hammasi oqib ketmaydi.",
  note: "turn off the water — suvni o'chirmoq.",
},

{
  num: 21,
  time: "00:01:30,079 --> 00:01:31,959",
  english: "Some of it stays down in the drain trap.",
  transcription: "sʌm əv ɪt steɪz daʊn ɪn ðə dreɪn træp",
  parts: [
    ["Some of it", "Uning bir qismi"],
    ["stays", "qoladi"],
    ["down", "pastda"],
    ["in the drain trap.", "oqova quvurining tutqichida."],
  ],
  uzbekFull: "Uning bir qismi oqova quvurining tutqichida pastda qoladi.",
  note: null,
},

{
  num: 22,
  time: "00:01:32,599 --> 00:01:37,000",
  english: "It's made that way so the smell from the sewer won't get back into the house.",
  transcription: "ɪts meɪd ðæt weɪ soʊ ðə smel frəm ðə ˈsuːər woʊnt ɡet bæk ˈɪntuː ðə haʊs",
  parts: [
    ["It's made", "U shunday yasalgan"],
    ["that way", "tarzda"],
    ["so", "shunda"],
    ["the smell", "hid"],
    ["from the sewer", "kanalizatsiyadan"],
    ["won't get back", "qaytib kelmaydi"],
    ["into the house.", "uy ichiga."],
  ],
  uzbekFull: "U shunday yasalganki, kanalizatsiyadagi hid uy ichiga qaytib kelmaydi.",
  note: "get back — qaytib kelmoq.",
},

{
  num: 23,
  time: "00:01:38,400 --> 00:01:40,400",
  english: "A ring is much heavier than water,",
  transcription: "ə rɪŋ ɪz mʌtʃ ˈheviər ðæn ˈwɔːtər",
  parts: [
    ["A ring", "Uzuk"],
    ["is", "bo'ladi"],
    ["much heavier", "ancha og'irroq"],
    ["than water,", "suvdan,"],
  ],
  uzbekFull: "Uzuk suvdan ancha og'irroq bo'ladi.",
  note: null,
},

{
  num: 24,
  time: "00:01:40,519 --> 00:01:43,560",
  english: "so if you happen to drop it down the drain, it won't wash away.",
  transcription: "soʊ ɪf juː ˈhæpən tə drɒp ɪt daʊn ðə dreɪn ɪt woʊnt wɒʃ əˈweɪ",
  parts: [
    ["so", "shuning uchun"],
    ["if you happen", "agar siz tasodifan"],
    ["to drop it", "uni tushirib yuborsangiz"],
    ["down the drain,", "oqova quvuriga,"],
    ["it won't", "u"],
    ["wash away.", "oqib ketmaydi."],
  ],
  uzbekFull: "Shuning uchun agar siz uni tasodifan oqova quvuriga tushirib yuborsangiz, u oqib ketmaydi.",
  note: "happen to — tasodifan.",
},

{
  num: 25,
  time: "00:01:43,719 --> 00:01:46,039",
  english: "It will stay at the bottom of the drain trap.",
  transcription: "ɪt wɪl steɪ æt ðə ˈbɒtəm əv ðə dreɪn træp",
  parts: [
    ["It will stay", "U qoladi"],
    ["at the bottom", "tubida"],
    ["of the drain trap.", "oqova quvurining tutqichining."],
  ],
  uzbekFull: "U oqova quvurining tutqichining tubida qoladi.",
  note: null,
},
{
  num: 26,
  time: "00:01:49,280 --> 00:01:51,480",
  english: "Well, that means we still got a chance!",
  transcription: "wel ðæt miːnz wiː stɪl ɡɒt ə tʃæns",
  parts: [
    ["Well,", "Xo'sh,"],
    ["that means", "bu degani"],
    ["we still", "bizda hali ham"],
    ["got a chance!", "imkon bor!"],
  ],
  uzbekFull: "Xo'sh, bu degani bizda hali ham imkon bor!",
  note: "got = have got (og'zaki nutqda).",
},

{
  num: 27,
  time: "00:01:51,640 --> 00:01:54,319",
  english: "Yeah, but how in the world can we get it out of that trap?",
  transcription: "jeə bʌt haʊ ɪn ðə wɜːrld kæn wiː ɡet ɪt aʊt əv ðæt træp",
  parts: [
    ["Yeah,", "Ha,"],
    ["but", "lekin"],
    ["how in the world", "qanday qilib o'zi"],
    ["can we get", "biz chiqara olamiz"],
    ["it", "uni"],
    ["out of", "ichidan"],
    ["that trap?", "o'sha tutqichning?"],
  ],
  uzbekFull: "Ha, lekin uni o'sha tutqich ichidan qanday qilib chiqaramiz?",
  note: "how in the world — qanday qilib o'zi.",
},

{
  num: 28,
  time: "00:01:54,640 --> 00:01:55,599",
  english: "Who knows?",
  transcription: "huː noʊz",
  parts: [
    ["Who knows?", "Kim biladi?"],
  ],
  uzbekFull: "Kim biladi?",
  note: null,
},

{
  num: 29,
  time: "00:01:55,599 --> 00:01:57,159",
  english: "I don't know how to swim.",
  transcription: "aɪ doʊnt noʊ haʊ tə swɪm",
  parts: [
    ["I don't know", "Men bilmayman"],
    ["how to swim.", "suzishni."],
  ],
  uzbekFull: "Men suzishni bilmayman.",
  note: null,
},

{
  num: 30,
  time: "00:01:57,159 --> 00:01:59,319",
  english: "Don't worry, it's all under control.",
  transcription: "doʊnt ˈwɜːri ɪts ɔːl ˈʌndər kənˈtroʊl",
  parts: [
    ["Don't worry,", "Xavotir olma,"],
    ["it's all", "hammasi"],
    ["under control.", "nazorat ostida."],
  ],
  uzbekFull: "Xavotir olma, hammasi nazorat ostida.",
  note: "under control — nazorat ostida.",
},

{
  num: 31,
  time: "00:01:59,599 --> 00:02:00,919",
  english: "Do you have any thread?",
  transcription: "duː juː hæv ˈeni θred",
  parts: [
    ["Do you have", "Senda bormi"],
    ["any thread?", "ip?"],
  ],
  uzbekFull: "Senda ip bormi?",
  note: "thread — ip.",
},

{
  num: 32,
  time: "00:02:01,159 --> 00:02:02,039",
  english: "Plenty of it.",
  transcription: "ˈplenti əv ɪt",
  parts: [
    ["Plenty", "Juda ko'p"],
    ["of it.", "bor."],
  ],
  uzbekFull: "Juda ko'p bor.",
  note: "plenty of — juda ko'p.",
},

{
  num: 33,
  time: "00:02:02,239 --> 00:02:04,719",
  english: "Go get it and I'll be back in a flash!",
  transcription: "ɡoʊ ɡet ɪt ænd aɪl biː bæk ɪn ə flæʃ",
  parts: [
    ["Go", "Bor"],
    ["get it", "olib kel uni"],
    ["and", "va"],
    ["I'll be back", "men qaytaman"],
    ["in a flash!", "bir zumda!"],
  ],
  uzbekFull: "Bor, uni olib kel, men bir zumda qaytaman!",
  note: "in a flash — bir zumda, juda tez.",
},

{
  num: 34,
  time: "00:02:07,959 --> 00:02:09,400",
  english: "I can't fix it like this.",
  transcription: "aɪ kænt fɪks ɪt laɪk ðɪs",
  parts: [
    ["I can't", "Men"],
    ["fix it", "uni tuzata olmayman"],
    ["like this.", "bunday."],
  ],
  uzbekFull: "Men uni bunday tuzata olmayman.",
  note: null,
},

{
  num: 35,
  time: "00:02:09,599 --> 00:02:10,799",
  english: "I need my welder.",
  transcription: "aɪ niːd maɪ ˈweldər",
  parts: [
    ["I need", "Menga kerak"],
    ["my welder.", "payvandlagichim."],
  ],
  uzbekFull: "Menga payvandlagichim kerak.",
  note: "welder — payvandlagich (asbob).",
},
{
  num: 36,
  time: "00:02:11,079 --> 00:02:12,000",
  english: "Papus!",
  transcription: "pəˈpuːs",
  parts: [
    ["Papus!", "Papus!"],
  ],
  uzbekFull: "Papus!",
  note: null,
},

{
  num: 37,
  time: "00:02:12,359 --> 00:02:14,959",
  english: "I need to borrow your pack-o-mat for a little while.",
  transcription: "aɪ niːd tə ˈbɒroʊ jʊr ˈpæk ə mæt fər ə ˈlɪtl waɪl",
  parts: [
    ["I need", "Menga kerak"],
    ["to borrow", "qarzga olish"],
    ["your pack-o-mat", "sening pack-o-matingni"],
    ["for a little while.", "bir oz vaqtga."],
  ],
  uzbekFull: "Sening pack-o-matingni bir oz vaqtga qarzga olishim kerak.",
  note: "borrow — qarzga olmoq.",
},

{
  num: 38,
  time: "00:02:15,199 --> 00:02:18,400",
  english: "Now that's a coincidence! I need to use it too!",
  transcription: "naʊ ðæts ə koʊˈɪnsɪdəns aɪ niːd tə juːz ɪt tuː",
  parts: [
    ["Now", "Ana endi"],
    ["that's", "bu"],
    ["a coincidence!", "tasodif ekan!"],
    ["I need", "Menga ham kerak"],
    ["to use it", "undan foydalanish"],
    ["too!", "ham!"],
  ],
  uzbekFull: "Ana endi bu tasodif ekan! Menga ham undan foydalanish kerak!",
  note: "coincidence — tasodif.",
},

{
  num: 39,
  time: "00:02:20,719 --> 00:02:23,479",
  english: "Masiya, then I need to use your pack-o-mat!",
  transcription: "məˈsiːjə ðen aɪ niːd tə juːz jʊr ˈpæk ə mæt",
  parts: [
    ["Masiya,", "Masiya,"],
    ["then", "unda"],
    ["I need", "menga kerak"],
    ["to use", "foydalanish"],
    ["your pack-o-mat!", "sening pack-o-matingdan!"],
  ],
  uzbekFull: "Masiya, unda menga sening pack-o-matingdan foydalanish kerak!",
  note: null,
},

{
  num: 40,
  time: "00:02:24,039 --> 00:02:24,560",
  english: "What?",
  transcription: "wʌt",
  parts: [
    ["What?", "Nima?"],
  ],
  uzbekFull: "Nima?",
  note: null,
},

{
  num: 41,
  time: "00:02:24,560 --> 00:02:25,800",
  english: "I'll bring it right back!",
  transcription: "aɪl brɪŋ ɪt raɪt bæk",
  parts: [
    ["I'll bring", "Men olib kelaman"],
    ["it", "uni"],
    ["right back!", "darrov qaytarib!"],
  ],
  uzbekFull: "Uni darrov qaytarib olib kelaman!",
  note: "right back — darhol, darrov.",
},

{
  num: 42,
  time: "00:02:25,800 --> 00:02:27,240",
  english: "Hey! Where are you going?",
  transcription: "heɪ wer ɑːr juː ˈɡoʊɪŋ",
  parts: [
    ["Hey!", "Hey!"],
    ["Where are", "Qayerga"],
    ["you going?", "ketyapsan?"],
  ],
  uzbekFull: "Hey! Qayerga ketyapsan?",
  note: null,
},

{
  num: 43,
  time: "00:02:27,240 --> 00:02:29,080",
  english: "Just watch what you're doing, dear!",
  transcription: "dʒʌst wɒtʃ wʌt jʊr ˈduːɪŋ dɪr",
  parts: [
    ["Just watch", "Ehtiyot bo'l"],
    ["what you're doing,", "nima qilayotganingga,"],
    ["dear!", "azizim!"],
  ],
  uzbekFull: "Azizim, nima qilayotganingga ehtiyot bo'l!",
  note: "watch what you're doing — ehtiyot bo'l, nima qilayotganingga qara.",
},

{
  num: 44,
  time: "00:02:34,719 --> 00:02:39,560",
  english: "Just like the name says, Fixies live to help machines and appliances.",
  transcription: "dʒʌst laɪk ðə neɪm sez ˈfɪksiz lɪv tə help məˈʃiːnz ænd əˈplaɪənsɪz",
  parts: [
    ["Just like", "Xuddi"],
    ["the name says,", "nomi aytganidek,"],
    ["Fixies", "Fikslar"],
    ["live", "yashaydi"],
    ["to help", "yordam berish uchun"],
    ["machines", "mashinalarga"],
    ["and appliances.", "va maishiy jihozlarga."],
  ],
  uzbekFull: "Nomi aytganidek, Fikslar mashinalar va maishiy jihozlarga yordam berish uchun yashaydi.",
  note: "appliance — maishiy jihoz.",
},

{
  num: 45,
  time: "00:02:39,759 --> 00:02:43,159",
  english: "But machines are very big and Fixies are very small,",
  transcription: "bʌt məˈʃiːnz ɑːr ˈveri bɪɡ ænd ˈfɪksiz ɑːr ˈveri smɔːl",
  parts: [
    ["But", "Lekin"],
    ["machines", "mashinalar"],
    ["are", "juda"],
    ["very big", "katta"],
    ["and", "esa"],
    ["Fixies", "Fikslar"],
    ["are", "juda"],
    ["very small,", "kichkina,"],
  ],
  uzbekFull: "Lekin mashinalar juda katta, Fikslar esa juda kichkina.",
  note: null,
},
{
  num: 46,
  time: "00:02:43,159 --> 00:02:45,360",
  english: "so they can't get by without tools.",
  transcription: "soʊ ðeɪ kænt ɡet baɪ wɪˈðaʊt tuːlz",
  parts: [
    ["so", "shuning uchun"],
    ["they can't", "ular qila olmaydi"],
    ["get by", "kun kechirishni"],
    ["without tools.", "asboblarsiz."],
  ],
  uzbekFull: "Shuning uchun ular asboblarsiz kun kechira olmaydi.",
  note: "get by — kun kechirmoq, ishni bitirmoq.",
},

{
  num: 47,
  time: "00:02:45,599 --> 00:02:49,680",
  english: "Long ago, Fixies worked with just about anything they could find.",
  transcription: "lɔːŋ əˈɡoʊ ˈfɪksiz wɜːrkt wɪð dʒʌst əˈbaʊt ˈeniθɪŋ ðeɪ kʊd faɪnd",
  parts: [
    ["Long ago,", "Qadimda,"],
    ["Fixies", "Fikslar"],
    ["worked", "ishlashardi"],
    ["with", "bilan"],
    ["just about anything", "topilgan deyarli har qanday narsa"],
    ["they could find.", "ular topa oladigan."],
  ],
  uzbekFull: "Qadimda Fikslar topa oladigan deyarli har qanday narsa bilan ishlashardi.",
  note: "just about anything — deyarli har qanday narsa.",
},

{
  num: 48,
  time: "00:02:49,800 --> 00:02:52,080",
  english: "Little feathers, threads, fins,",
  transcription: "ˈlɪtl ˈfeðərz θredz fɪnz",
  parts: [
    ["Little feathers,", "Kichkina patlar,"],
    ["threads,", "iplar,"],
    ["fins,", "qanotchalar,"],
  ],
  uzbekFull: "Kichkina patlar, iplar, qanotchalar.",
  note: "fin — qanotcha, suzgich.",
},

{
  num: 49,
  time: "00:02:52,080 --> 00:02:55,120",
  english: "But now they have backpacks called pack-o-mats.",
  transcription: "bʌt naʊ ðeɪ hæv ˈbækˌpæks kɔːld ˈpæk ə mæts",
  parts: [
    ["But now", "Lekin hozir"],
    ["they have", "ularda bor"],
    ["backpacks", "ryukzaklar"],
    ["called", "deb ataladigan"],
    ["pack-o-mats.", "pack-o-matlar."],
  ],
  uzbekFull: "Lekin hozir ularda pack-o-matlar deb ataladigan ryukzaklar bor.",
  note: null,
},

{
  num: 50,
  time: "00:02:55,200 --> 00:02:58,320",
  english: "Inside a pack-o-mat are all sorts of tools.",
  transcription: "ɪnˈsaɪd ə ˈpæk ə mæt ɑːr ɔːl sɔːrts əv tuːlz",
  parts: [
    ["Inside", "Ichida"],
    ["a pack-o-mat", "pack-o-matning"],
    ["are", "bor"],
    ["all sorts of", "har xil"],
    ["tools.", "asboblar."],
  ],
  uzbekFull: "Pack-o-matning ichida har xil asboblar bor.",
  note: "all sorts of — har xil.",
},

{
  num: 51,
  time: "00:02:58,400 --> 00:03:01,439",
  english: "Just push the button and the pack-o-mat spins around",
  transcription: "dʒʌst pʊʃ ðə ˈbʌtn ænd ðə ˈpæk ə mæt spɪnz əˈraʊnd",
  parts: [
    ["Just", "Shunchaki"],
    ["push", "bosing"],
    ["the button", "tugmani"],
    ["and", "va"],
    ["the pack-o-mat", "pack-o-mat"],
    ["spins around.", "aylana boshlaydi."],
  ],
  uzbekFull: "Shunchaki tugmani bosing va pack-o-mat aylana boshlaydi.",
  note: "spin around — aylanmoq.",
},

{
  num: 52,
  time: "00:03:01,520 --> 00:03:05,439",
  english: "quickly shooting out a hook, or a magnet, or even a parachute.",
  transcription: "ˈkwɪkli ˈʃuːtɪŋ aʊt ə hʊk ɔːr ə ˈmæɡnət ɔːr ˈiːvən ə ˈpærəʃuːt",
  parts: [
    ["quickly", "tezda"],
    ["shooting out", "chiqarib yuborib"],
    ["a hook,", "ilgakni,"],
    ["or a magnet,", "yoki magnitni,"],
    ["or even", "hatto yoki"],
    ["a parachute.", "parashyutni."],
  ],
  uzbekFull: "U tezda ilgakni, magnitni yoki hatto parashyutni chiqarib yuboradi.",
  note: "shoot out — tez chiqarib yubormoq.",
},

{
  num: 53,
  time: "00:03:05,560 --> 00:03:08,320",
  english: "Every adult Fixie has their own pack-o-mat.",
  transcription: "ˈevri əˈdʌlt ˈfɪksi hæz ðer oʊn ˈpæk ə mæt",
  parts: [
    ["Every", "Har bir"],
    ["adult Fixie", "katta Fiks"],
    ["has", "ega"],
    ["their own", "o'zining"],
    ["pack-o-mat.", "pack-o-matiga."],
  ],
  uzbekFull: "Har bir katta Fiks o'zining pack-o-matiga ega.",
  note: null,
},

{
  num: 54,
  time: "00:03:08,439 --> 00:03:12,200",
  english: "But before children can get them, they have to go to school and study hard,",
  transcription: "bʌt bɪˈfɔːr ˈtʃɪldrən kæn ɡet ðem ðeɪ hæv tə ɡoʊ tə skuːl ænd ˈstʌdi hɑːrd",
  parts: [
    ["But before", "Lekin oldin"],
    ["children", "bolalar"],
    ["can get", "ola olishidan"],
    ["them,", "ularni,"],
    ["they have", "ular kerak"],
    ["to go", "borishi"],
    ["to school", "maktabga"],
    ["and study", "va o'qishi"],
    ["hard,", "qattiq,"],
  ],
  uzbekFull: "Lekin bolalar ularni olishidan oldin maktabga borishi va qattiq o'qishi kerak.",
  note: null,
},
{
  num: 55,
  time: "00:03:12,280 --> 00:03:15,600",
  english: "and then pass an exam before they have the rights of a full-fledged Fixie.",
  transcription: "ænd ðen pæs ən ɪɡˈzæm bɪˈfɔːr ðeɪ hæv ðə raɪts əv ə ˌfʊlˈfledʒd ˈfɪksi",
  parts: [
    ["and then", "va keyin"],
    ["pass", "topshirishi"],
    ["an exam", "imtihonni"],
    ["before", "oldin"],
    ["they have", "ular ega bo'lishidan"],
    ["the rights", "huquqlariga"],
    ["of", "bo'lgan"],
    ["a full-fledged", "to'liq huquqli"],
    ["Fixie.", "Fiksning."],
  ],
  uzbekFull: "Va keyin to'liq huquqli Fiks bo'lish huquqini olishdan oldin imtihonni topshirishi kerak.",
  note: "full-fledged — to'liq huquqli.",
},

{
  num: 56,
  time: "00:03:15,680 --> 00:03:19,200",
  english: "And it's only after all of that that young Fixies get their own pack-o-mats.",
  transcription: "ænd ɪts ˈoʊnli ˈæftər ɔːl əv ðæt ðæt jʌŋ ˈfɪksiz ɡet ðer oʊn ˈpæk ə mæts",
  parts: [
    ["And", "Va"],
    ["it's only", "faqat"],
    ["after", "keyin"],
    ["all of that", "shularning hammasidan"],
    ["that", "shundagina"],
    ["young Fixies", "yosh Fikslar"],
    ["get", "oladi"],
    ["their own", "o'z"],
    ["pack-o-mats.", "pack-o-matlarini."],
  ],
  uzbekFull: "Va faqat shularning hammasidan keyingina yosh Fikslar o'z pack-o-matlarini oladi.",
  note: null,
},

{
  num: 57,
  time: "00:03:22,080 --> 00:03:26,440",
  english: "And what? You're going down there with just that on?",
  transcription: "ænd wʌt jʊr ˈɡoʊɪŋ daʊn ðer wɪð dʒʌst ðæt ɒn",
  parts: [
    ["And what?", "Nima deding?"],
    ["You're going", "Sen tushmoqchimisan"],
    ["down there", "u yerga pastga"],
    ["with", "faqat"],
    ["just that on?", "shuni kiygan holda?"],
  ],
  uzbekFull: "Nima deding? Sen u yerga pastga faqat shuni kiygan holda tushmoqchimisan?",
  note: "have ... on — ustida kiyib turmoq.",
},

{
  num: 58,
  time: "00:03:26,440 --> 00:03:27,800",
  english: "Not just like this!",
  transcription: "nɒt dʒʌst laɪk ðɪs",
  parts: [
    ["Not", "Yo'q,"],
    ["just like this!", "faqat bunday emas!"],
  ],
  uzbekFull: "Yo'q, faqat bunday emas!",
  note: null,
},

{
  num: 59,
  time: "00:03:31,120 --> 00:03:32,280",
  english: "Like this?",
  transcription: "laɪk ðɪs",
  parts: [
    ["Like this?", "Shundaymi?"],
  ],
  uzbekFull: "Shundaymi?",
  note: null,
},

{
  num: 60,
  time: "00:03:32,600 --> 00:03:33,920",
  english: "Yeah, like that!",
  transcription: "jeə laɪk ðæt",
  parts: [
    ["Yeah,", "Ha,"],
    ["like that!", "xuddi shunday!"],
  ],
  uzbekFull: "Ha, xuddi shunday!",
  note: null,
},

{
  num: 61,
  time: "00:03:34,240 --> 00:03:37,640",
  english: "When I tug the thread, pull me up!",
  transcription: "wen aɪ tʌɡ ðə θred pʊl miː ʌp",
  parts: [
    ["When", "Qachonki"],
    ["I tug", "men tortsam"],
    ["the thread,", "ipni,"],
    ["pull", "tort"],
    ["me up!", "meni tepaga!"],
  ],
  uzbekFull: "Qachonki men ipni tortsam, meni tepaga tort!",
  note: "tug — qattiq tortmoq.",
},

{
  num: 62,
  time: "00:03:38,760 --> 00:03:39,920",
  english: "She was just saying,",
  transcription: "ʃiː wəz dʒʌst ˈseɪɪŋ",
  parts: [
    ["She", "U"],
    ["was just saying,", "hozirgina aytayotgandi,"],
  ],
  uzbekFull: "U hozirgina aytayotgandi,",
  note: null,
},

{
  num: 63,
  time: "00:03:40,000 --> 00:03:42,640",
  english: "when I tug on the thread, you need to pull me up!",
  transcription: "wen aɪ tʌɡ ɒn ðə θred juː niːd tə pʊl miː ʌp",
  parts: [
    ["when", "qachonki"],
    ["I tug", "men tortsam"],
    ["on the thread,", "ipni,"],
    ["you need", "sening kerak"],
    ["to pull", "tortishing"],
    ["me up!", "meni tepaga!"],
  ],
  uzbekFull: "Qachonki men ipni tortsam, sen meni tepaga tortishing kerak!",
  note: "tug on — tortmoq.",
},

{
  num: 64,
  time: "00:03:42,640 --> 00:03:43,480",
  english: "I got it!",
  transcription: "aɪ ɡɒt ɪt",
  parts: [
    ["I got it!", "Tushundim!"],
  ],
  uzbekFull: "Tushundim!",
  note: "I got it! — Tushundim!",
},
{
  num: 65,
  time: "00:03:43,560 --> 00:03:44,439",
  english: "He just said,",
  transcription: "hiː dʒʌst sed",
  parts: [
    ["He", "U"],
    ["just said,", "hozirgina aytdi,"],
  ],
  uzbekFull: "U hozirgina aytdi,",
  note: null,
},

{
  num: 66,
  time: "00:03:44,680 --> 00:03:45,439",
  english: "I got it.",
  transcription: "aɪ ɡɒt ɪt",
  parts: [
    ["I got it.", "Tushundim."],
  ],
  uzbekFull: "Tushundim.",
  note: null,
},

{
  num: 67,
  time: "00:03:45,600 --> 00:03:47,880",
  english: "And I don't need to repeat what he says.",
  transcription: "ænd aɪ doʊnt niːd tə rɪˈpiːt wʌt hiː sez",
  parts: [
    ["And", "Va"],
    ["I don't need", "menga kerak emas"],
    ["to repeat", "takrorlash"],
    ["what he says.", "uning aytganini."],
  ],
  uzbekFull: "Va menga uning aytganini takrorlash kerak emas.",
  note: "repeat — takrorlamoq.",
},

{
  num: 68,
  time: "00:03:47,880 --> 00:03:50,640",
  english: "She said she doesn't need me to repeat what you say.",
  transcription: "ʃiː sed ʃiː ˈdʌzənt niːd miː tə rɪˈpiːt wʌt juː seɪ",
  parts: [
    ["She said", "U aytdi"],
    ["she doesn't need", "unga kerak emasligini"],
    ["me", "mening"],
    ["to repeat", "takrorlashim"],
    ["what you say.", "sen aytganingni."],
  ],
  uzbekFull: "U sen aytganingni mening takrorlashim kerak emasligini aytdi.",
  note: null,
},

{
  num: 69,
  time: "00:03:52,080 --> 00:03:57,080",
  english: "[Music]",
  transcription: null,
  parts: [
    ["[Music]", "[Musiqa]"],
  ],
  uzbekFull: "[Musiqa]",
  note: null,
},

{
  num: 70,
  time: "00:04:22,079 --> 00:04:31,959",
  english: "Simka, Nolik, thank you. You really saved the day.",
  transcription: "ˈsɪmkə ˈnoʊlɪk θæŋk juː juː ˈrɪəli seɪvd ðə deɪ",
  parts: [
    ["Simka, Nolik,", "Simka, Nolik,"],
    ["thank you.", "rahmat sizlarga."],
    ["You really", "Sizlar haqiqatan ham"],
    ["saved the day.", "vaziyatni saqlab qoldingiz."],
  ],
  uzbekFull: "Simka, Nolik, rahmat sizlarga. Sizlar haqiqatan ham vaziyatni saqlab qoldingiz.",
  note: "save the day — vaziyatni saqlab qolmoq, hammasini o'nglamoq.",
},

{
  num: 71,
  time: "00:04:32,599 --> 00:04:34,120",
  english: "That's what Simka's for!",
  transcription: "ðæts wʌt ˈsɪmkəz fɔːr",
  parts: [
    ["That's", "Shuning uchun"],
    ["what", "kerak"],
    ["Simka's for!", "Simka!"],
  ],
  uzbekFull: "Simka aynan shuning uchun kerak!",
  note: "be for — ... uchun bo'lmoq.",
},

{
  num: 72,
  time: "00:04:34,879 --> 00:04:37,199",
  english: "I said that's what Fixies are for!",
  transcription: "aɪ sed ðæts wʌt ˈfɪksiz ɑːr fɔːr",
  parts: [
    ["I said", "Men aytdim"],
    ["that's", "shuning uchun"],
    ["what", "kerak"],
    ["Fixies are for!", "Fikslar!"],
  ],
  uzbekFull: "Men Fikslar aynan shuning uchun kerak dedim!",
  note: null,
},

{
  num: 73,
  time: "00:04:37,279 --> 00:04:39,719",
  english: "Tom Thomas, who are you talking with in there?",
  transcription: "tɒm ˈtɒməs huː ɑːr juː ˈtɔːkɪŋ wɪð ɪn ðer",
  parts: [
    ["Tom Thomas,", "Tom Tomas,"],
    ["who are", "kim bilan"],
    ["you talking", "gaplashyapsan"],
    ["with", ""],
    ["in there?", "u yerda?"],
  ],
  uzbekFull: "Tom Tomas, u yerda kim bilan gaplashyapsan?",
  note: "talk with — bilan gaplashmoq.",
},
{
  num: 74,
  time: "00:04:39,959 --> 00:04:41,439",
  english: "Oh, your mom came back!",
  transcription: "oʊ jʊr mɑːm keɪm bæk",
  parts: [
    ["Oh,", "Voy,"],
    ["your mom", "oying"],
    ["came back!", "qaytib keldi!"],
  ],
  uzbekFull: "Voy, oying qaytib keldi!",
  note: "come back — qaytib kelmoq.",
},

{
  num: 75,
  time: "00:04:44,639 --> 00:04:45,439",
  english: "No one.",
  transcription: "noʊ wʌn",
  parts: [
    ["No one.", "Hech kim."],
  ],
  uzbekFull: "Hech kim.",
  note: null,
},

{
  num: 76,
  time: "00:04:48,799 --> 00:04:50,719",
  english: "Hey, can you turn back into Fixies?",
  transcription: "heɪ kæn juː tɜːrn bæk ˈɪntuː ˈfɪksiz",
  parts: [
    ["Hey,", "Hey,"],
    ["can you", "siz"],
    ["turn back", "yana aylana olasizmi"],
    ["into Fixies?", "Fikslarga?"],
  ],
  uzbekFull: "Hey, siz yana Fikslarga aylana olasizmi?",
  note: "turn back into — yana ...ga aylanmoq.",
},

{
  num: 77,
  time: "00:04:50,720 --> 00:04:52,280",
  english: "I've got to ask you a question.",
  transcription: "aɪv ɡɒt tə æsk juː ə ˈkwestʃən",
  parts: [
    ["I've got", "Men"],
    ["to ask", "so'rashim kerak"],
    ["you", "sizdan"],
    ["a question.", "bir savolni."],
  ],
  uzbekFull: "Men sizdan bir savol so'rashim kerak.",
  note: "have got to = have to.",
},

{
  num: 78,
  time: "00:04:52,840 --> 00:04:57,800",
  english: "I forgot. Should I write '12th anniversary' with an F or do I write it with a V?",
  transcription: "aɪ fərˈɡɒt ʃʊd aɪ raɪt twelfθ ˌænɪˈvɜːrsəri wɪð ən ef ɔːr duː aɪ raɪt ɪt wɪð ə viː",
  parts: [
    ["I forgot.", "Esimdan chiqibdi."],
    ["Should I write", "Yozaymi"],
    ["12th anniversary", "12th anniversary"],
    ["with an F", "F harfi bilan"],
    ["or", "yoki"],
    ["do I write it", "uni yozaymi"],
    ["with a V?", "V harfi bilan?"],
  ],
  uzbekFull: "Esimdan chiqibdi. '12th anniversary'ni F harfi bilan yozaymi yoki V harfi bilan?",
  note: null,
},

{
  num: 79,
  time: "00:04:58,160 --> 00:04:59,760",
  english: "Just write the number!",
  transcription: "dʒʌst raɪt ðə ˈnʌmbər",
  parts: [
    ["Just", "Shunchaki"],
    ["write", "yoz"],
    ["the number!", "raqamni!"],
  ],
  uzbekFull: "Shunchaki raqamni yoz!",
  note: null,
},

{
  num: 80,
  time: "00:05:00,360 --> 00:05:01,280",
  english: "You're right!",
  transcription: "jʊr raɪt",
  parts: [
    ["You're right!", "To'g'ri ekansan!"],
  ],
  uzbekFull: "To'g'ri ekansan!",
  note: null,
}
];
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = lessons;
}