const lesons = [
 {
  num: 1,
  time: "00:00:00,000 --> 00:00:04,820",
  english: "Ramadan, the month of Ramadan is almost here.",
  transcription: "ˌræməˈdɑːn ðə mʌnθ əv ˌræməˈdɑːn ɪz ˈɔːlmoʊst hɪr",
  parts: [
    ["Ramadan,", "Ramazon,"],
    ["the month", "oyi"],
    ["of Ramadan", "Ramazonning"],
    ["is almost here.", "deyarli kirib keldi."],
  ],
  uzbekFull: "Ramazon, Ramazon oyi deyarli kirib keldi.",
  note: null,
},

{
  num: 2,
  time: "00:00:05,280 --> 00:00:07,839",
  english: "We've waited a long way, we've waited a while.",
  transcription: "wiːv ˈweɪtɪd ə lɔːŋ weɪ wiːv ˈweɪtɪd ə waɪl",
  parts: [
    ["We've waited", "Biz kutdik"],
    ["a long way,", "uzoq vaqt,"],
    ["we've waited", "biz kutdik"],
    ["a while.", "bir muddat."],
  ],
  uzbekFull: "Biz uzoq vaqt, ancha muddat kutdik.",
  note: "wait a while — bir muddat kutmoq.",
},

{
  num: 3,
  time: "00:00:07,839 --> 00:00:12,900",
  english: "for the month of mercy, for the month of mercy,",
  transcription: "fɔːr ðə mʌnθ əv ˈmɜːrsi fɔːr ðə mʌnθ əv ˈmɜːrsi",
  parts: [
    ["for", "uchun"],
    ["the month", "oyni"],
    ["of mercy,", "rahmatning,"],
    ["for", "uchun"],
    ["the month", "oyni"],
    ["of mercy,", "rahmatning,"],
  ],
  uzbekFull: "Rahmat oyini, rahmat oyini kutdik.",
  note: "mercy — rahmat, marhamat.",
},

{
  num: 4,
  time: "00:00:13,240 --> 00:00:20,420",
  english: "for the month of mercy, Ramadan, the month of mercy.",
  transcription: "fɔːr ðə mʌnθ əv ˈmɜːrsi ˌræməˈdɑːn ðə mʌnθ əv ˈmɜːrsi",
  parts: [
    ["for", "uchun"],
    ["the month", "oyni"],
    ["of mercy,", "rahmatning,"],
    ["Ramadan,", "Ramazon,"],
    ["the month", "oyi"],
    ["of mercy.", "rahmatning."],
  ],
  uzbekFull: "Rahmat oyini, Ramazonni — rahmat oyini kutdik.",
  note: null,
},

{
  num: 5,
  time: "00:00:25,420 --> 00:00:29,960",
  english: "Ramadan lesson number one, Taqwa or Faith.",
  transcription: "ˌræməˈdɑːn ˈlesən ˈnʌmbər wʌn ˈtækwɑː ɔːr feɪθ",
  parts: [
    ["Ramadan", "Ramazon"],
    ["lesson", "darsi"],
    ["number one,", "birinchi,"],
    ["Taqwa", "Taqvo"],
    ["or", "yoki"],
    ["Faith.", "imon."],
  ],
  uzbekFull: "Ramazonning birinchi darsi: Taqvo yoki imon.",
  note: "faith — imon.",
},

{
  num: 6,
  time: "00:00:30,000 --> 00:00:33,119",
  english: "Why do we fast in the month of Ramadan?",
  transcription: "waɪ duː wiː fæst ɪn ðə mʌnθ əv ˌræməˈdɑːn",
  parts: [
    ["Why", "Nima uchun"],
    ["do we fast", "biz ro'za tutamiz"],
    ["in", "da"],
    ["the month", "oyida"],
    ["of Ramadan?", "Ramazonning?"],
  ],
  uzbekFull: "Nima uchun biz Ramazon oyida ro'za tutamiz?",
  note: "fast (verb) — ro'za tutmoq.",
},

{
  num: 7,
  time: "00:00:33,939 --> 00:00:39,039",
  english: "One of the main reasons is to increase our obedience to Allah subhanahu wa ta'ala.",
  transcription: "wʌn əv ðə meɪn ˈriːzənz ɪz tə ɪnˈkriːs ˌaʊər əˈbiːdiəns tə əˈlɑːh",
  parts: [
    ["One", "Bittasi"],
    ["of the main reasons", "asosiy sabablardan"],
    ["is", "bu"],
    ["to increase", "oshirish"],
    ["our obedience", "itoatimizni"],
    ["to Allah", "Allohga."],
  ],
  uzbekFull: "Asosiy sabablardan biri Allohga bo'lgan itoatimizni oshirishdir.",
  note: "obedience — itoat, bo'ysunish.",
},

{
  num: 8,
  time: "00:00:39,740 --> 00:00:47,140",
  english: "Sometimes we forget our Creator, Allah subhanahu wa ta'ala, during our happy times and our bad times.",
  transcription: "ˈsʌmtaɪmz wiː fərˈɡet ˌaʊər kriˈeɪtər əˈlɑːh ˈdjʊrɪŋ ˈaʊər ˈhæpi taɪmz ænd ˈaʊər bæd taɪmz",
  parts: [
    ["Sometimes", "Ba'zan"],
    ["we forget", "biz unutamiz"],
    ["our Creator,", "Yaratuvchimizni,"],
    ["Allah,", "Allohni,"],
    ["during", "davomida"],
    ["our happy times", "quvonchli vaqtlarimizda"],
    ["and", "va"],
    ["our bad times.", "og'ir vaqtlarimizda."],
  ],
  uzbekFull: "Ba'zan biz quvonchli va og'ir vaqtlarimizda Yaratuvchimiz Allohni unutamiz.",
  note: "Creator — Yaratuvchi.",
},
{
  num: 9,
  time: "00:00:48,320 --> 00:00:51,439",
  english: "Ramadan helps us to remember Allah subhanahu wa ta'ala more.",
  transcription: "ˌræməˈdɑːn helps ʌs tə rɪˈmembər əˈlɑːh mɔːr",
  parts: [
    ["Ramadan", "Ramazon"],
    ["helps us", "bizga yordam beradi"],
    ["to remember", "eslashga"],
    ["Allah", "Allohni"],
    ["more.", "ko'proq."],
  ],
  uzbekFull: "Ramazon bizga Allohni ko'proq eslashga yordam beradi.",
  note: null,
},

{
  num: 10,
  time: "00:00:51,920 --> 00:00:58,600",
  english: "During the month of Ramadan, it helps us to avoid all of the bad things that Allah doesn't like.",
  transcription: "ˈdjʊrɪŋ ðə mʌnθ əv ˌræməˈdɑːn ɪt helps ʌs tə əˈvɔɪd ɔːl əv ðə bæd θɪŋz ðæt əˈlɑːh ˈdʌzənt laɪk",
  parts: [
    ["During", "Davomida"],
    ["the month", "oyining"],
    ["of Ramadan,", "Ramazon,"],
    ["it helps us", "u bizga yordam beradi"],
    ["to avoid", "saqlanishga"],
    ["all of", "barcha"],
    ["the bad things", "yomon narsalardan"],
    ["that", "qaysiki"],
    ["Allah", "Alloh"],
    ["doesn't like.", "yoqtirmaydi."],
  ],
  uzbekFull: "Ramazon oyi davomida u bizga Alloh yoqtirmaydigan barcha yomon narsalardan saqlanishga yordam beradi.",
  note: "avoid — chetlanmoq, saqlanmoq.",
},

{
  num: 11,
  time: "00:00:58,600 --> 00:01:06,400",
  english: "So that means that we have the opportunity to do all the things that Allah subhanahu wa ta'ala wants us to do.",
  transcription: "soʊ ðæt miːnz ðæt wiː hæv ði ˌɒpərˈtuːnəti tə duː ɔːl ðə θɪŋz ðæt əˈlɑːh wɒnts ʌs tə duː",
  parts: [
    ["So", "Demak"],
    ["that means", "bu degani"],
    ["that", "ki"],
    ["we have", "bizda bor"],
    ["the opportunity", "imkoniyat"],
    ["to do", "qilish"],
    ["all the things", "barcha narsalarni"],
    ["that", "qaysilarni"],
    ["Allah", "Alloh"],
    ["wants us", "bizdan xohlaydi"],
    ["to do.", "qilishimizni."],
  ],
  uzbekFull: "Demak, bizda Alloh bizdan qilishni xohlagan barcha ishlarni qilish imkoniyati bor.",
  note: "opportunity — imkoniyat.",
},

{
  num: 12,
  time: "00:01:07,219 --> 00:01:14,819",
  english: "That's why, to increase our taqwa or faith, Allah subhanahu wa ta'ala orders us to fast in this month.",
  transcription: "ðæts waɪ tə ɪnˈkriːs ˈaʊər ˈtækwɑː ɔːr feɪθ əˈlɑːh ˈɔːrdərz ʌs tə fæst ɪn ðɪs mʌnθ",
  parts: [
    ["That's why,", "Shuning uchun,"],
    ["to increase", "oshirish uchun"],
    ["our taqwa", "taqvomizni"],
    ["or faith,", "yoki imonimizni,"],
    ["Allah", "Alloh"],
    ["orders us", "bizga buyuradi"],
    ["to fast", "ro'za tutishni"],
    ["in this month.", "bu oyda."],
  ],
  uzbekFull: "Shuning uchun Alloh taqvomizni yoki imonimizni oshirish uchun bizga bu oyda ro'za tutishni buyuradi.",
  note: "order (verb) — buyurmoq.",
},

{
  num: 13,
  time: "00:01:15,920 --> 00:01:19,219",
  english: "If you see the second part of our Prophet Musa's story,",
  transcription: "ɪf juː siː ðə ˈsekənd pɑːrt əv ˈaʊər ˈprɒfɪt ˈmuːsəz ˈstɔːri",
  parts: [
    ["If", "Agar"],
    ["you see", "siz ko'rsangiz"],
    ["the second part", "ikkinchi qismini"],
    ["of", "ning"],
    ["our Prophet Musa's", "Payg'ambarimiz Musoning"],
    ["story,", "qissasini,"],
  ],
  uzbekFull: "Agar Payg'ambarimiz Muso qissasining ikkinchi qismini ko'rsangiz,",
  note: null,
},

{
  num: 14,
  time: "00:01:20,540 --> 00:01:26,879",
  english: "you will see that after a long journey of trying to escape from Pharaoh,",
  transcription: "juː wɪl siː ðæt ˈæftər ə lɔːŋ ˈdʒɜːrni əv ˈtraɪɪŋ tə ɪˈskeɪp frəm ˈferoʊ",
  parts: [
    ["you will see", "siz ko'rasiz"],
    ["that", "ki"],
    ["after", "keyin"],
    ["a long journey", "uzoq safardan"],
    ["of trying", "harakat qilish"],
    ["to escape", "qochishga"],
    ["from Pharaoh,", "Fir'avndan,"],
  ],
  uzbekFull: "siz Fir'avndan qochishga urinishdagi uzoq safardan keyin ekanini ko'rasiz.",
  note: "Pharaoh — Fir'avn.",
},
{
  num: 15,
  time: "00:01:27,659 --> 00:01:33,420",
  english: "Prophet Musa and his people arrived on the east side of Mount Sinai.",
  transcription: "ˈprɒfɪt ˈmuːsə ænd hɪz ˈpiːpəl əˈraɪvd ɒn ði iːst saɪd əv maʊnt ˈsaɪnaɪ",
  parts: [
    ["Prophet Musa", "Payg'ambar Muso"],
    ["and", "va"],
    ["his people", "uning qavmi"],
    ["arrived", "yetib keldi"],
    ["on", "ga"],
    ["the east side", "sharqiy tomoniga"],
    ["of Mount Sinai.", "Sinay tog'ining."],
  ],
  uzbekFull: "Payg'ambar Muso va uning qavmi Sinay tog'ining sharqiy tomoniga yetib keldi.",
  note: null,
},

{
  num: 16,
  time: "00:01:34,439 --> 00:01:42,340",
  english: "Allah subhanahu wa ta'ala told Musa, peace be upon him, to go to that same place where he talked to Allah subhanahu wa ta'ala for the first time.",
  transcription: "əˈlɑːh toʊld ˈmuːsə piːs biː əˈpɒn hɪm tə ɡoʊ tə ðæt seɪm pleɪs wer hiː tɔːkt tə əˈlɑːh fər ðə fɜːrst taɪm",
  parts: [
    ["Allah", "Alloh"],
    ["told", "buyurdi"],
    ["Musa,", "Musoga,"],
    ["to go", "borishni"],
    ["to", "ga"],
    ["that same place", "o'sha joyning o'ziga"],
    ["where", "u yerda"],
    ["he talked", "u gaplashgan"],
    ["to Allah", "Alloh bilan"],
    ["for the first time.", "birinchi marta."],
  ],
  uzbekFull: "Alloh Musoga birinchi marta Alloh bilan gaplashgan o'sha joyning o'ziga borishni buyurdi.",
  note: null,
},

{
  num: 17,
  time: "00:01:43,379 --> 00:01:48,099",
  english: "At that place, he had to stay and fast for 30 days.",
  transcription: "æt ðæt pleɪs hiː hæd tə steɪ ænd fæst fər ˈθɜːrti deɪz",
  parts: [
    ["At", "O'sha"],
    ["that place,", "joyda,"],
    ["he had to", "u kerak edi"],
    ["stay", "qolishi"],
    ["and fast", "va ro'za tutishi"],
    ["for 30 days.", "30 kun davomida."],
  ],
  uzbekFull: "O'sha joyda u 30 kun davomida qolishi va ro'za tutishi kerak edi.",
  note: "have to — majbur bo'lmoq.",
},

{
  num: 18,
  time: "00:01:49,019 --> 00:01:58,640",
  english: "After the 30 days of fasting and praying, Allah subhanahu wa ta'ala told him to do 10 more days to continue his prayer and fasting.",
  transcription: "ˈæftər ðə ˈθɜːrti deɪz əv ˈfæstɪŋ ænd ˈpreɪɪŋ əˈlɑːh toʊld hɪm tə duː ten mɔːr deɪz tə kənˈtɪnjuː hɪz prer ænd ˈfæstɪŋ",
  parts: [
    ["After", "Keyin"],
    ["the 30 days", "30 kun"],
    ["of fasting", "ro'za tutish"],
    ["and praying,", "va ibodat qilishdan,"],
    ["Allah", "Alloh"],
    ["told him", "unga buyurdi"],
    ["to do", "davom ettirishni"],
    ["10 more days", "yana 10 kun"],
    ["to continue", "davom ettirish uchun"],
    ["his prayer", "ibodatini"],
    ["and fasting.", "va ro'zasini."],
  ],
  uzbekFull: "30 kun ro'za tutib, ibodat qilganidan keyin Alloh unga ibodati va ro'zasini davom ettirish uchun yana 10 kunni davom ettirishni buyurdi.",
  note: null,
},

{
  num: 19,
  time: "00:01:59,619 --> 00:02:06,000",
  english: "In total, he spent 40 days fasting and praying to increase his taqwa.",
  transcription: "ɪn ˈtoʊtl hiː spent ˈfɔːrti deɪz ˈfæstɪŋ ænd ˈpreɪɪŋ tə ɪnˈkriːs hɪz ˈtækwɑː",
  parts: [
    ["In total,", "Jami,"],
    ["he spent", "u o'tkazdi"],
    ["40 days", "40 kunni"],
    ["fasting", "ro'za tutib"],
    ["and praying", "va ibodat qilib"],
    ["to increase", "oshirish uchun"],
    ["his taqwa.", "taqvosini."],
  ],
  uzbekFull: "Jami u taqvosini oshirish uchun 40 kunni ro'za tutib va ibodat qilib o'tkazdi.",
  note: null,
},

{
  num: 20,
  time: "00:02:06,659 --> 00:02:17,340",
  english: "Then Allah subhanahu wa ta'ala gave Prophet Musa, peace be upon him, some parts of the Holy Torah, which were the famous Ten Commandments.",
  transcription: "ðen əˈlɑːh ɡeɪv ˈprɒfɪt ˈmuːsə sʌm pɑːrts əv ðə ˈhoʊli ˈtɔːrə wɪtʃ wɜːr ðə ˈfeɪməs ten kəˈmændmənts",
  parts: [
    ["Then", "So'ng"],
    ["Allah", "Alloh"],
    ["gave", "berdi"],
    ["Prophet Musa", "Payg'ambar Musoga"],
    ["some parts", "ba'zi qismlarini"],
    ["of the Holy Torah,", "Tavrotning,"],
    ["which were", "ular edi"],
    ["the famous", "mashhur"],
    ["Ten Commandments.", "O'nta amr."],
  ],
  uzbekFull: "So'ng Alloh Payg'ambar Musoga Tavrotning mashhur O'nta amrni o'z ichiga olgan ba'zi qismlarini berdi.",
  note: "Ten Commandments — O'nta amr.",
},
{
  num: 21,
  time: "00:02:18,099 --> 00:02:23,460",
  english: "Just like Musa, peace be upon him, spent 40 days to increase his faith,",
  transcription: "dʒʌst laɪk ˈmuːsə spent ˈfɔːrti deɪz tə ɪnˈkriːs hɪz feɪθ",
  parts: [
    ["Just like", "Xuddi"],
    ["Musa,", "Muso"],
    ["spent", "o'tkazganidek"],
    ["40 days", "40 kunni"],
    ["to increase", "oshirish uchun"],
    ["his faith,", "imonini,"],
  ],
  uzbekFull: "Xuddi Muso imonini oshirish uchun 40 kun o'tkazganidek,",
  note: null,
},

{
  num: 22,
  time: "00:02:24,280 --> 00:02:31,280",
  english: "we do the same thing during the month of Ramadan in order to increase our taqwa.",
  transcription: "wiː duː ðə seɪm θɪŋ ˈdjʊrɪŋ ðə mʌnθ əv ˌræməˈdɑːn ɪn ˈɔːrdər tə ɪnˈkriːs ˈaʊər ˈtækwɑː",
  parts: [
    ["we do", "biz qilamiz"],
    ["the same thing", "xuddi shu ishni"],
    ["during", "davomida"],
    ["the month", "oyining"],
    ["of Ramadan", "Ramazon"],
    ["in order", "uchun"],
    ["to increase", "oshirish"],
    ["our taqwa.", "taqvomizni."],
  ],
  uzbekFull: "Biz ham Ramazon oyi davomida taqvomizni oshirish uchun xuddi shu ishni qilamiz.",
  note: "in order to — ... uchun.",
},

{
  num: 23,
  time: "00:02:32,120 --> 00:02:38,340",
  english: "That's why we shouldn't let our Ramadan go to waste by playing games or sleeping around all day",
  transcription: "ðæts waɪ wiː ˈʃʊdnt let ˈaʊər ˌræməˈdɑːn ɡoʊ tə weɪst baɪ ˈpleɪɪŋ ɡeɪmz ɔːr ˈsliːpɪŋ əˈraʊnd ɔːl deɪ",
  parts: [
    ["That's why", "Shuning uchun"],
    ["we shouldn't", "biz kerak emas"],
    ["let", "yo'l qo'yishimiz"],
    ["our Ramadan", "Ramazonimizning"],
    ["go to waste", "bekorga o'tishiga"],
    ["by playing games", "o'yin o'ynab"],
    ["or", "yoki"],
    ["sleeping around", "uxlab yurib"],
    ["all day", "kun bo'yi."],
  ],
  uzbekFull: "Shuning uchun Ramazonimizning o'yin o'ynab yoki kun bo'yi uxlab bekorga o'tishiga yo'l qo'ymasligimiz kerak.",
  note: "go to waste — bekorga ketmoq.",
},

{
  num: 24,
  time: "00:02:38,340 --> 00:02:43,539",
  english: "because every moment of Ramadan is valuable.",
  transcription: "bɪˈkɒz ˈevri ˈmoʊmənt əv ˌræməˈdɑːn ɪz ˈvæljuəbl",
  parts: [
    ["because", "chunki"],
    ["every moment", "har bir lahzasi"],
    ["of Ramadan", "Ramazonning"],
    ["is valuable.", "qimmatlidir."],
  ],
  uzbekFull: "Chunki Ramazonning har bir lahzasi qimmatlidir.",
  note: "valuable — qimmatli.",
},

{
  num: 25,
  time: "00:02:43,539 --> 00:02:57,739",
  english: "Some ways that we can increase our taqwa is by spending our time reading the Qur'an, memorizing some surahs, or memorizing some important du'as from the Qur'an.",
  transcription: "sʌm weɪz ðæt wiː kæn ɪnˈkriːs ˈaʊər ˈtækwɑː ɪz baɪ ˈspendɪŋ ˈaʊər taɪm ˈriːdɪŋ ðə kʊˈrɑːn ˈmeməraɪzɪŋ sʌm ˈsʊrəz ɔːr ˈmeməraɪzɪŋ sʌm ɪmˈpɔːrtnt duˈɑːz frəm ðə kʊˈrɑːn",
  parts: [
    ["Some ways", "Ba'zi yo'llar"],
    ["that", "qanday qilib"],
    ["we can increase", "biz oshirishimiz mumkin"],
    ["our taqwa", "taqvomizni"],
    ["is by", "— bu"],
    ["spending", "sarflash"],
    ["our time", "vaqtimizni"],
    ["reading", "o'qishga"],
    ["the Qur'an,", "Qur'onni,"],
    ["memorizing", "yodlashga"],
    ["some surahs,", "ba'zi suralarni,"],
    ["or", "yoki"],
    ["memorizing", "yodlashga"],
    ["some important", "ba'zi muhim"],
    ["du'as", "duolarni"],
    ["from the Qur'an.", "Qur'ondan."],
  ],
  uzbekFull: "Taqvomizni oshirish yo'llaridan ba'zilari vaqtimizni Qur'on o'qishga, ba'zi suralarni yoki Qur'ondagi ba'zi muhim duolarni yodlashga sarflashdir.",
  note: "memorize — yodlamoq.",
},
{
  num: 26,
  time: "00:02:58,159 --> 00:03:06,819",
  english: "You can actually find lots of very important Qur'anic du'as along with their background information from our channel.",
  transcription: "juː kæn ˈæktʃuəli faɪnd lɒts əv ˈveri ɪmˈpɔːrtnt kʊrˈænɪk duˈɑːz əˈlɒŋ wɪð ðer ˈbækɡraʊnd ˌɪnfərˈmeɪʃən frəm ˈaʊər ˈtʃænəl",
  parts: [
    ["You can", "Siz mumkin"],
    ["actually find", "haqiqatan topishingiz"],
    ["lots of", "juda ko'p"],
    ["very important", "juda muhim"],
    ["Qur'anic du'as", "Qur'oniy duolarni"],
    ["along with", "ular bilan birga"],
    ["their background information", "ularning izohlarini"],
    ["from our channel.", "kanalimizdan."],
  ],
  uzbekFull: "Siz kanalimizdan juda muhim Qur'oniy duolarni va ularning izohlarini topishingiz mumkin.",
  note: "along with — bilan birga.",
},

{
  num: 27,
  time: "00:03:06,819 --> 00:03:13,560",
  english: "If you want to memorize some verses from the Qur'an, don't wait for tomorrow.",
  transcription: "ɪf juː wɒnt tə ˈmeməraɪz sʌm ˈvɜːrsɪz frəm ðə kʊˈrɑːn doʊnt weɪt fər təˈmɒroʊ",
  parts: [
    ["If", "Agar"],
    ["you want", "siz xohlasangiz"],
    ["to memorize", "yodlashni"],
    ["some verses", "ba'zi oyatlarni"],
    ["from the Qur'an,", "Qur'ondan,"],
    ["don't wait", "kutmang"],
    ["for tomorrow.", "ertagacha."],
  ],
  uzbekFull: "Agar Qur'ondan ba'zi oyatlarni yodlamoqchi bo'lsangiz, ertagacha kutmang.",
  note: "verse — oyat.",
},

{
  num: 28,
  time: "00:03:14,280 --> 00:03:17,939",
  english: "Start today to memorize something from the Qur'an.",
  transcription: "stɑːrt təˈdeɪ tə ˈmeməraɪz ˈsʌmθɪŋ frəm ðə kʊˈrɑːn",
  parts: [
    ["Start", "Boshlang"],
    ["today", "bugun"],
    ["to memorize", "yodlashni"],
    ["something", "biror narsani"],
    ["from the Qur'an.", "Qur'ondan."],
  ],
  uzbekFull: "Bugundan Qur'ondan biror narsani yodlashni boshlang.",
  note: null,
},

{
  num: 29,
  time: "00:03:19,159 --> 00:03:25,060",
  english: "Also, we can read some Islamic books to get more knowledge about Islam.",
  transcription: "ˈɔːlsoʊ wiː kæn riːd sʌm ɪzˈlæmɪk bʊks tə ɡet mɔːr ˈnɒlɪdʒ əˈbaʊt ɪzˈlɑːm",
  parts: [
    ["Also,", "Shuningdek,"],
    ["we can", "biz mumkin"],
    ["read", "o'qishimiz"],
    ["some Islamic books", "ba'zi islomiy kitoblarni"],
    ["to get", "olish uchun"],
    ["more knowledge", "ko'proq bilim"],
    ["about Islam.", "Islom haqida."],
  ],
  uzbekFull: "Shuningdek, Islom haqida ko'proq bilim olish uchun ba'zi islomiy kitoblarni o'qishimiz mumkin.",
  note: "knowledge — bilim.",
},

{
  num: 30,
  time: "00:03:25,419 --> 00:03:34,019",
  english: "Along with memorizing, in order to increase our taqwa, we can also go to the mosque for our prayers.",
  transcription: "əˈlɒŋ wɪð ˈmeməraɪzɪŋ ɪn ˈɔːrdər tə ɪnˈkriːs ˈaʊər ˈtækwɑː wiː kæn ˈɔːlsoʊ ɡoʊ tə ðə mɒsk fər ˈaʊər prerz",
  parts: [
    ["Along with", "Bilan birga"],
    ["memorizing,", "yodlashning,"],
    ["in order", "uchun"],
    ["to increase", "oshirish"],
    ["our taqwa,", "taqvomizni,"],
    ["we can", "biz mumkin"],
    ["also go", "yana borishimiz"],
    ["to the mosque", "masjidga"],
    ["for our prayers.", "namozlarimiz uchun."],
  ],
  uzbekFull: "Yodlash bilan birga, taqvomizni oshirish uchun namozlarimizni o'qish maqsadida masjidga ham borishimiz mumkin.",
  note: "mosque — masjid.",
},

{
  num: 31,
  time: "00:03:34,020 --> 00:03:40,820",
  english: "That way we can get 27 more rewards than praying at home.",
  transcription: "ðæt weɪ wiː kæn ɡet ˈtwenti ˈsevən mɔːr rɪˈwɔːrdz ðæn ˈpreɪɪŋ æt hoʊm",
  parts: [
    ["That way", "Shu yo'l bilan"],
    ["we can get", "biz olishimiz mumkin"],
    ["27 more", "27 ta ko'proq"],
    ["rewards", "savob"],
    ["than", "ga qaraganda"],
    ["praying", "namoz o'qish"],
    ["at home.", "uyda."],
  ],
  uzbekFull: "Shu yo'l bilan uyda namoz o'qishga qaraganda 27 ta ko'proq savob olishimiz mumkin.",
  note: "reward — savob, mukofot.",
},

{
  num: 32,
  time: "00:03:40,820 --> 00:03:46,260",
  english: "But when we go to the mosque during the month of Ramadan,",
  transcription: "bʌt wen wiː ɡoʊ tə ðə mɒsk ˈdjʊrɪŋ ðə mʌnθ əv ˌræməˈdɑːn",
  parts: [
    ["But", "Lekin"],
    ["when", "qachonki"],
    ["we go", "biz borsak"],
    ["to the mosque", "masjidga"],
    ["during", "davomida"],
    ["the month", "oyining"],
    ["of Ramadan,", "Ramazon,"],
  ],
  uzbekFull: "Lekin Ramazon oyi davomida masjidga borsak,",
  note: null,
},
{
  num: 33,
  time: "00:03:46,260 --> 00:03:51,300",
  english: "Allah subhanahu wa ta'ala will give us even more rewards than that.",
  transcription: "əˈlɑːh wɪl ɡɪv ʌs ˈiːvən mɔːr rɪˈwɔːrdz ðæn ðæt",
  parts: [
    ["Allah", "Alloh"],
    ["will give", "beradi"],
    ["us", "bizga"],
    ["even more", "bundan ham ko'proq"],
    ["rewards", "savoblar"],
    ["than that.", "undan."],
  ],
  uzbekFull: "Alloh bizga bundan ham ko'proq savob beradi.",
  note: null,
},

{
  num: 34,
  time: "00:03:51,300 --> 00:03:55,040",
  english: "But let's say that we cannot go to the mosque.",
  transcription: "bʌt lets seɪ ðæt wiː ˈkænɒt ɡoʊ tə ðə mɒsk",
  parts: [
    ["But", "Lekin"],
    ["let's say", "faraz qilaylik"],
    ["that", "ki"],
    ["we cannot", "biz bora olmaymiz"],
    ["go", "borishga"],
    ["to the mosque.", "masjidga."],
  ],
  uzbekFull: "Lekin faraz qilaylik, biz masjidga bora olmaymiz.",
  note: "let's say — faraz qilaylik.",
},

{
  num: 35,
  time: "00:03:55,040 --> 00:03:57,600",
  english: "So what do we do then?",
  transcription: "soʊ wʌt duː wiː duː ðen",
  parts: [
    ["So", "Unda"],
    ["what", "nima"],
    ["do we do", "qilamiz"],
    ["then?", "endi?"],
  ],
  uzbekFull: "Unda endi nima qilamiz?",
  note: null,
},

{
  num: 36,
  time: "00:03:57,599 --> 00:04:07,560",
  english: "If we can't go, we should pray at home as a group with our parents, our brothers and sisters, or with our friends.",
  transcription: "ɪf wiː kænt ɡoʊ wiː ʃʊd preɪ æt hoʊm æz ə ɡruːp wɪð ˈaʊər ˈperənts ˈaʊər ˈbrʌðərz ænd ˈsɪstərz ɔːr wɪð ˈaʊər frendz",
  parts: [
    ["If", "Agar"],
    ["we can't go,", "biz bora olmasak,"],
    ["we should", "biz kerak"],
    ["pray", "namoz o'qishimiz"],
    ["at home", "uyda"],
    ["as a group", "jamoa bo'lib"],
    ["with", "bilan"],
    ["our parents,", "ota-onamiz,"],
    ["our brothers", "aka-uka va"],
    ["and sisters,", "opa-singillarimiz,"],
    ["or", "yoki"],
    ["with our friends.", "do'stlarimiz bilan."],
  ],
  uzbekFull: "Agar biz bora olmasak, ota-onamiz, aka-uka va opa-singillarimiz yoki do'stlarimiz bilan uyda jamoa bo'lib namoz o'qishimiz kerak.",
  note: "as a group — jamoa bo'lib.",
},

{
  num: 37,
  time: "00:04:08,000 --> 00:04:18,000",
  english: "Another thing that we should do during Ramadan is donate money every day with whatever we have, even if it's a small amount.",
  transcription: "əˈnʌðər θɪŋ ðæt wiː ʃʊd duː ˈdjʊrɪŋ ˌræməˈdɑːn ɪz ˈdoʊneɪt ˈmʌni ˈevri deɪ wɪð wʌtˈevər wiː hæv ˈiːvən ɪf ɪts ə smɔːl əˈmaʊnt",
  parts: [
    ["Another thing", "Yana bir narsa"],
    ["that", "qaysiki"],
    ["we should do", "biz qilishimiz kerak"],
    ["during Ramadan", "Ramazon davomida"],
    ["is", "— bu"],
    ["donate money", "pul sadaqa qilish"],
    ["every day", "har kuni"],
    ["with", "qo'limizdagi"],
    ["whatever we have,", "nima bo'lsa ham,"],
    ["even if", "hatto agar"],
    ["it's", "u"],
    ["a small amount.", "oz miqdor bo'lsa ham."],
  ],
  uzbekFull: "Ramazon davomida qilishimiz kerak bo'lgan yana bir narsa — qo'limizdagi narsa qancha bo'lishidan qat'i nazar, har kuni sadaqa qilishdir, hatto u oz miqdor bo'lsa ham.",
  note: "donate — ehson qilmoq, sadaqa bermoq.",
},

{
  num: 38,
  time: "00:04:18,639 --> 00:04:25,740",
  english: "If you want to increase your money, then the only way to do that is by donating your money for Allah.",
  transcription: "ɪf juː wɒnt tə ɪnˈkriːs jʊr ˈmʌni ðen ði ˈoʊnli weɪ tə duː ðæt ɪz baɪ doʊˈneɪtɪŋ jʊr ˈmʌni fər əˈlɑːh",
  parts: [
    ["If", "Agar"],
    ["you want", "siz xohlasangiz"],
    ["to increase", "ko'paytirishni"],
    ["your money,", "pulingizni,"],
    ["then", "unda"],
    ["the only way", "yagona yo'l"],
    ["to do that", "buni qilishning"],
    ["is", "— bu"],
    ["by donating", "ehson qilish"],
    ["your money", "pulingizni"],
    ["for Allah.", "Alloh yo'lida."],
  ],
  uzbekFull: "Agar pulingizni ko'paytirishni istasangiz, buning yagona yo'li pulingizni Alloh yo'lida ehson qilishdir.",
  note: "the only way — yagona yo'l.",
},
{
  num: 39,
  time: "00:04:25,740 --> 00:04:32,100",
  english: "By that way, Allah subhanahu wa ta'ala will increase your money and return it to you in some sort of way, insha'Allah.",
  transcription: "baɪ ðæt weɪ əˈlɑːh wɪl ɪnˈkriːs jʊr ˈmʌni ænd rɪˈtɜːrn ɪt tə juː ɪn sʌm sɔːrt əv weɪ ɪnʃɑːˈɑːlɑːh",
  parts: [
    ["By that way,", "Shu yo'l bilan,"],
    ["Allah", "Alloh"],
    ["will increase", "ko'paytiradi"],
    ["your money", "pulingizni"],
    ["and", "va"],
    ["return", "qaytaradi"],
    ["it", "uni"],
    ["to you", "sizga"],
    ["in some sort of way,", "biror yo'l bilan,"],
    ["insha'Allah.", "inshaAlloh."],
  ],
  uzbekFull: "Shu yo'l bilan Alloh pulingizni ko'paytiradi va uni sizga biror yo'l bilan qaytaradi, inshaAlloh.",
  note: "return — qaytarmoq.",
},

{
  num: 40,
  time: "00:04:32,100 --> 00:04:38,900",
  english: "When you're donating your money, it is important to remember",
  transcription: "wen jʊr doʊˈneɪtɪŋ jʊr ˈmʌni ɪt ɪz ɪmˈpɔːrtnt tə rɪˈmembər",
  parts: [
    ["When", "Qachonki"],
    ["you're donating", "siz ehson qilayotgan bo'lsangiz"],
    ["your money,", "pulingizni,"],
    ["it is", "bu"],
    ["important", "muhim"],
    ["to remember", "eslab qolish."],
  ],
  uzbekFull: "Pulingizni ehson qilayotganingizda, buni eslab qolish muhim.",
  note: null,
},

{
  num: 41,
  time: "00:04:38,900 --> 00:04:49,519",
  english: "that any donations that you give are like water for hellfire.",
  transcription: "ðæt ˈeni doʊˈneɪʃənz ðæt juː ɡɪv ɑːr laɪk ˈwɔːtər fər ˈhelfaɪər",
  parts: [
    ["that", "ki"],
    ["any donations", "har qanday ehsonlar"],
    ["that", "qaysilarni"],
    ["you give", "siz bersangiz"],
    ["are like", "o'xshaydi"],
    ["water", "suvga"],
    ["for hellfire.", "do'zax olovi uchun."],
  ],
  uzbekFull: "Siz bergan har qanday ehson do'zax olovi uchun suv kabidir.",
  note: "hellfire — do'zax olovi.",
},

{
  num: 42,
  time: "00:04:49,519 --> 00:04:57,899",
  english: "Another important way that we can increase our taqwa is to respect our parents at all times by listening to our parents",
  transcription: "əˈnʌðər ɪmˈpɔːrtnt weɪ ðæt wiː kæn ɪnˈkriːs ˈaʊər ˈtækwɑː ɪz tə rɪˈspekt ˈaʊər ˈperənts æt ɔːl taɪmz baɪ ˈlɪsənɪŋ tə ˈaʊər ˈperənts",
  parts: [
    ["Another", "Yana bir"],
    ["important way", "muhim yo'l"],
    ["that", "qanday qilib"],
    ["we can increase", "biz oshirishimiz mumkin"],
    ["our taqwa", "taqvomizni"],
    ["is", "— bu"],
    ["to respect", "hurmat qilish"],
    ["our parents", "ota-onamizni"],
    ["at all times", "har doim"],
    ["by listening", "quloq solish orqali"],
    ["to our parents.", "ota-onamizga."],
  ],
  uzbekFull: "Taqvomizni oshirishning yana bir muhim yo'li — har doim ota-onamizga quloq solib, ularni hurmat qilishdir.",
  note: "respect — hurmat qilmoq.",
},

{
  num: 43,
  time: "00:04:57,899 --> 00:05:05,099",
  english: "and helping them out during Ramadan. We should always listen to our parents and you can help",
  transcription: "ænd ˈhelpɪŋ ðem aʊt ˈdjʊrɪŋ ˌræməˈdɑːn wiː ʃʊd ˈɔːlweɪz ˈlɪsən tə ˈaʊər ˈperənts ænd juː kæn help",
  parts: [
    ["and helping", "va yordam berish"],
    ["them out", "ularga"],
    ["during Ramadan.", "Ramazon davomida."],
    ["We should", "Biz kerak"],
    ["always listen", "doimo quloq solishimiz"],
    ["to our parents", "ota-onamizga"],
    ["and", "va"],
    ["you can help", "siz yordam bera olasiz"],
  ],
  uzbekFull: "Ramazon davomida ularga yordam berishimiz kerak. Biz doimo ota-onamizga quloq solishimiz kerak va siz yordam bera olasiz.",
  note: "help someone out — kimgadir yordam bermoq.",
},
{
  num: 44,
  time: "00:05:05,099 --> 00:05:14,000",
  english: "them during Ramadan in many ways. Finally, if we do the good deeds during Ramadan, insha'Allah,",
  transcription: "ðem ˈdjʊrɪŋ ˌræməˈdɑːn ɪn ˈmeni weɪz ˈfaɪnəli ɪf wiː duː ðə ɡʊd diːdz ˈdjʊrɪŋ ˌræməˈdɑːn ɪnʃɑːˈɑːlɑːh",
  parts: [
    ["them", "ularga"],
    ["during Ramadan", "Ramazon davomida"],
    ["in many ways.", "ko'p yo'llar bilan."],
    ["Finally,", "Nihoyat,"],
    ["if", "agar"],
    ["we do", "biz qilsak"],
    ["the good deeds", "yaxshi amallarni"],
    ["during Ramadan,", "Ramazon davomida,"],
    ["insha'Allah,", "inshaAlloh,"],
  ],
  uzbekFull: "Ramazon davomida ularga ko'p yo'llar bilan yordam bera olasiz. Nihoyat, agar Ramazon davomida yaxshi amallarni qilsak, inshaAlloh,",
  note: "good deeds — yaxshi amallar.",
},

{
  num: 45,
  time: "00:05:14,000 --> 00:05:17,720",
  english: "Allah subhanahu wa ta'ala will increase our taqwa.",
  transcription: "əˈlɑːh wɪl ɪnˈkriːs ˈaʊər ˈtækwɑː",
  parts: [
    ["Allah", "Alloh"],
    ["will increase", "oshiradi"],
    ["our taqwa.", "taqvomizni."],
  ],
  uzbekFull: "Alloh taqvomizni oshiradi.",
  note: null,
},

{
  num: 46,
  time: "00:05:17,720 --> 00:05:23,240",
  english: "For more information, you can look up Surah Muhammad, verse 17.",
  transcription: "fɔːr mɔːr ˌɪnfərˈmeɪʃən juː kæn lʊk ʌp ˈsʊrə ˈmʊhæməd vɜːrs ˌsevənˈtiːn",
  parts: [
    ["For", "Qo'shimcha"],
    ["more information,", "ma'lumot uchun,"],
    ["you can", "siz mumkin"],
    ["look up", "qarashingiz"],
    ["Surah Muhammad,", "Muhammad surasiga,"],
    ["verse 17.", "17-oyatga."],
  ],
  uzbekFull: "Qo'shimcha ma'lumot uchun Muhammad surasining 17-oyatiga qarashingiz mumkin.",
  note: "look up — izlab topmoq, murojaat qilmoq.",
},

{
  num: 47,
  time: "00:05:23,240 --> 00:05:26,100",
  english: "Al-Fath, verse 4.",
  transcription: "æl ˈfætħ vɜːrs fɔːr",
  parts: null,
  uzbekFull: "Fath surasi, 4-oyat.",
  note: null,
},

{
  num: 48,
  time: "00:05:26,100 --> 00:05:29,459",
  english: "An-Nisa, verse 103.",
  transcription: "æn nɪˈsɑːʔ vɜːrs wʌn ˈhʌndrəd θriː",
  parts: null,
  uzbekFull: "Niso surasi, 103-oyat.",
  note: null,
},

{
  num: 49,
  time: "00:05:29,459 --> 00:05:33,500",
  english: "Al-Ankabut, verse 45.",
  transcription: "æl ˌænkəˈbuːt vɜːrs ˌfɔːrti ˈfaɪv",
  parts: null,
  uzbekFull: "Ankabut surasi, 45-oyat.",
  note: null,
},

{
  num: 50,
  time: "00:05:33,500 --> 00:05:36,839",
  english: "Sad, verse 29.",
  transcription: "sɑːd vɜːrs ˌtwenti ˈnaɪn",
  parts: null,
  uzbekFull: "Sod surasi, 29-oyat.",
  note: null,
},

{
  num: 51,
  time: "00:05:36,839 --> 00:05:41,500",
  english: "And Taha, verse 114.",
  transcription: "ænd ˈtɑːhɑː vɜːrs wʌn ˈhʌndrəd fɔːrˈtiːn",
  parts: null,
  uzbekFull: "Va Toha surasi, 114-oyat.",
  note: null,
},
{
  num: 52,
  time: "00:05:41,500 --> 00:05:55,120",
  english: "Have you ever wanted to make a big difference to help children all over the world?",
  transcription: "hæv juː ˈevər ˈwɒntɪd tə meɪk ə bɪɡ ˈdɪfrəns tə help ˈtʃɪldrən ɔːl ˈoʊvər ðə wɜːrld",
  parts: [
    ["Have you ever", "Siz hech qachon"],
    ["wanted", "xohlaganmisiz"],
    ["to make", "qilishni"],
    ["a big difference", "katta o'zgarish"],
    ["to help", "yordam berish uchun"],
    ["children", "bolalarga"],
    ["all over", "butun"],
    ["the world?", "dunyo bo'ylab?"],
  ],
  uzbekFull: "Siz hech qachon butun dunyo bo'ylab bolalarga yordam berish uchun katta o'zgarish qilishni xohlaganmisiz?",
  note: "make a difference — muhim ijobiy o'zgarish qilmoq.",
},

{
  num: 53,
  time: "00:05:55,939 --> 00:06:00,139",
  english: "Well, what if we told you that you can make that difference happen right now",
  transcription: "wel wʌt ɪf wiː toʊld juː ðæt juː kæn meɪk ðæt ˈdɪfrəns ˈhæpən raɪt naʊ",
  parts: [
    ["Well,", "Xo'sh,"],
    ["what if", "agar"],
    ["we told you", "sizga aytsakchi"],
    ["that", "ki"],
    ["you can", "siz mumkin"],
    ["make", "amalga oshirish"],
    ["that difference", "o'sha o'zgarishni"],
    ["happen", "ro'y berishini"],
    ["right now.", "hoziroq."],
  ],
  uzbekFull: "Xo'sh, agar sizga o'sha o'zgarishni hoziroq amalga oshira olishingizni aytsak-chi?",
  note: "what if... — ... bo'lsa-chi?",
},

{
  num: 54,
  time: "00:06:00,139 --> 00:06:02,920",
  english: "with our Ramadan fundraiser 2018.",
  transcription: "wɪð ˈaʊər ˌræməˈdɑːn ˈfʌndˌreɪzər ˌtwenti ˌeɪˈtiːn",
  parts: [
    ["with", "orqali"],
    ["our", "bizning"],
    ["Ramadan fundraiser", "Ramazon xayriya kampaniyamiz"],
    ["2018.", "2018."],
  ],
  uzbekFull: "Bizning 2018-yilgi Ramazon xayriya kampaniyamiz orqali.",
  note: "fundraiser — xayriya mablag' yig'ish tadbiri.",
},

{
  num: 55,
  time: "00:06:04,139 --> 00:06:08,680",
  english: "We provide everything we create for free and are committed to keeping it that way",
  transcription: "wiː prəˈvaɪd ˈevriθɪŋ wiː kriˈeɪt fər friː ænd ɑːr kəˈmɪtɪd tə ˈkiːpɪŋ ɪt ðæt weɪ",
  parts: [
    ["We provide", "Biz taqdim etamiz"],
    ["everything", "hamma narsani"],
    ["we create", "yaratadiganimizni"],
    ["for free", "bepul"],
    ["and", "va"],
    ["are committed", "qat'iy bel bog'laganmiz"],
    ["to keeping", "saqlab qolishga"],
    ["it", "uni"],
    ["that way.", "shundayligicha."],
  ],
  uzbekFull: "Biz yaratadigan barcha narsani bepul taqdim etamiz va uni shundayligicha saqlab qolishga qat'iy bel bog'laganmiz.",
  note: "be committed to — qat'iy bel bog'lamoq.",
},

{
  num: 56,
  time: "00:06:08,680 --> 00:06:13,120",
  english: "for millions of Muslims and non-Muslims all over the world.",
  transcription: "fər ˈmɪljənz əv ˈmʊzlɪmz ænd nɒn ˈmʊzlɪmz ɔːl ˈoʊvər ðə wɜːrld",
  parts: [
    ["for", "uchun"],
    ["millions of", "millionlab"],
    ["Muslims", "musulmonlar"],
    ["and", "va"],
    ["non-Muslims", "musulmon bo'lmaganlar"],
    ["all over", "butun"],
    ["the world.", "dunyo bo'ylab."],
  ],
  uzbekFull: "Butun dunyo bo'ylab millionlab musulmonlar va musulmon bo'lmaganlar uchun.",
  note: null,
},

{
  num: 57,
  time: "00:06:14,600 --> 00:06:20,000",
  english: "One hundred percent of our operations are crowdfunded from our generous audience.",
  transcription: "wʌn ˈhʌndrəd pərˈsent əv ˈaʊər ˌɒpəˈreɪʃənz ɑːr ˈkraʊdˌfʌndɪd frəm ˈaʊər ˈdʒenərəs ˈɔːdiəns",
  parts: [
    ["One hundred percent", "Yuz foizi"],
    ["of our operations", "faoliyatimizning"],
    ["are crowdfunded", "jamoaviy moliyalashtiriladi"],
    ["from", "tomonidan"],
    ["our generous audience.", "saxiy auditoriyamiz."],
  ],
  uzbekFull: "Faoliyatimizning yuz foizi saxiy auditoriyamiz tomonidan jamoaviy moliyalashtiriladi.",
  note: "crowdfunded — jamoaviy mablag' bilan moliyalashtirilgan.",
},

{
  num: 58,
  time: "00:06:20,900 --> 00:06:26,180",
  english: "We want to continue our dawah mission and we can do so with your help.",
  transcription: "wiː wɒnt tə kənˈtɪnjuː ˈaʊər ˈdæwə ˈmɪʃən ænd wiː kæn duː soʊ wɪð jʊr help",
  parts: [
    ["We want", "Biz xohlaymiz"],
    ["to continue", "davom ettirishni"],
    ["our dawah mission", "da'vat missiyamizni"],
    ["and", "va"],
    ["we can", "biz qila olamiz"],
    ["do so", "buni"],
    ["with your help.", "sizning yordamingiz bilan."],
  ],
  uzbekFull: "Biz da'vat missiyamizni davom ettirishni xohlaymiz va buni sizning yordamingiz bilan qila olamiz.",
  note: "do so — shunday qilmoq.",
},
{
  num: 59,
  time: "00:06:26,960 --> 00:06:31,139",
  english: "All donations are tax deductible and sadaqah jariyah,",
  transcription: "ɔːl doʊˈneɪʃənz ɑːr tæks dɪˈdʌktəbl ænd səˈdɑːqə dʒɑːriə",
  parts: [
    ["All donations", "Barcha ehsonlar"],
    ["are", "hisoblanadi"],
    ["tax deductible", "soliqdan chegiriladigan"],
    ["and", "hamda"],
    ["sadaqah jariyah,", "sadaqai joriya."],
  ],
  uzbekFull: "Barcha ehsonlar soliqdan chegiriladigan hisoblanadi va sadaqai joriyadir.",
  note: "tax deductible — soliqdan chegiriladigan.",
},

{
  num: 60,
  time: "00:06:31,139 --> 00:06:35,759",
  english: "which continues to benefit you when you pass away from this world.",
  transcription: "wɪtʃ kənˈtɪnjuːz tə ˈbenɪfɪt juː wen juː pæs əˈweɪ frəm ðɪs wɜːrld",
  parts: [
    ["which", "u"],
    ["continues", "davom etadi"],
    ["to benefit", "foyda berishda"],
    ["you", "sizga"],
    ["when", "qachonki"],
    ["you pass away", "siz vafot etsangiz"],
    ["from this world.", "bu dunyodan."],
  ],
  uzbekFull: "U siz bu dunyodan vafot etganingizdan keyin ham sizga foyda berishda davom etadi.",
  note: "pass away — vafot etmoq.",
},

{
  num: 61,
  time: "00:06:35,759 --> 00:06:39,680",
  english: "As Ramadan is the best rewarding month of the year",
  transcription: "æz ˌræməˈdɑːn ɪz ðə best rɪˈwɔːrdɪŋ mʌnθ əv ðə jɪr",
  parts: [
    ["As", "Chunki"],
    ["Ramadan", "Ramazon"],
    ["is", "hisoblanadi"],
    ["the best", "eng yaxshi"],
    ["rewarding month", "savobli oy"],
    ["of the year.", "yilning."],
  ],
  uzbekFull: "Chunki Ramazon yilning eng savobli oyidir.",
  note: "rewarding — savobi ko'p, serajr.",
},

{
  num: 62,
  time: "00:06:39,680 --> 00:06:43,099",
  english: "Please join our Ramadan fundraiser 2018.",
  transcription: "pliːz dʒɔɪn ˈaʊər ˌræməˈdɑːn ˈfʌndˌreɪzər ˌtwenti ˌeɪˈtiːn",
  parts: [
    ["Please", "Iltimos"],
    ["join", "qo'shiling"],
    ["our", "bizning"],
    ["Ramadan fundraiser", "Ramazon xayriya kampaniyamizga"],
    ["2018.", "2018."],
  ],
  uzbekFull: "Iltimos, bizning 2018-yilgi Ramazon xayriya kampaniyamizga qo'shiling.",
  note: null,
},

{
  num: 63,
  time: "00:06:43,099 --> 00:06:47,219",
  english: "May Allah subhanahu wa ta'ala accept your generosity.",
  transcription: "meɪ əˈlɑːh əkˈsept jʊr ˌdʒenəˈrɒsəti",
  parts: [
    ["May", "Nasib etsin"],
    ["Allah", "Alloh"],
    ["accept", "qabul qilsin"],
    ["your generosity.", "saxovatingizni."],
  ],
  uzbekFull: "Alloh saxovatingizni qabul qilsin.",
  note: "generosity — saxovat.",
},

{
  num: 64,
  time: "00:06:47,219 --> 00:06:53,379",
  english: "And may Allah subhanahu wa ta'ala give the highest reward to you and your family.",
  transcription: "ænd meɪ əˈlɑːh ɡɪv ðə ˈhaɪəst rɪˈwɔːrd tə juː ænd jʊr ˈfæməli",
  parts: [
    ["And", "Va"],
    ["may", "nasib etsin"],
    ["Allah", "Alloh"],
    ["give", "bersin"],
    ["the highest", "eng ulug'"],
    ["reward", "mukofotni"],
    ["to you", "sizga"],
    ["and", "va"],
    ["your family.", "oilangizga."],
  ],
  uzbekFull: "Va Alloh sizga hamda oilangizga eng ulug' mukofotni bersin.",
  note: null,
},

{
  num: 65,
  time: "00:06:53,379 --> 00:06:56,439",
  english: "In this world and the hereafter.",
  transcription: "ɪn ðɪs wɜːrld ænd ði ˈhɪrˌæftər",
  parts: [
    ["In", "Bu"],
    ["this world", "dunyoda"],
    ["and", "va"],
    ["the hereafter.", "oxiratda."],
  ],
  uzbekFull: "Bu dunyoda va oxiratda.",
  note: "the hereafter — oxirat.",
}];
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = lessons;
}